language: python

python:
  - "3.11.9"

install:
  - pip install pipenv
  - pip install safety
  - pip install -q pipenv codecov
  - pipenv sync --dev
  - cp contrib/env-sample.env

script:
  - flake8 .
  - isort .
  - black .
  - pipenv run pytest
  - coverage run manage.py test --noinput
  - coverage report --show-missing
  - pipenv run pytest


after_success:
  - coveralls
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
    - COVERALLS_REPO_TOKEN=4wTG5MYJHXtIZiD1s4KZqb4q1J187gTcS
    - name: pyupio/safety-action
      uses: pyupio/safety-action@v1.0.1
            