language: python

python:
  - "3.11.9"

install:
  - pip install safety
  - pip install -q pipenv codecov
  - pipenv sync --dev

script:
  - flake8 .
  - isort .
  - black .
  - python manage.py test
  - coverage run manage.py test --noinput
  - coverage report --show-missing
  - safety check -r requirements-dev.txt

after_success:
  - coveralls
env:
  global:
    - COVERALLS_REPO_TOKEN=4wTG5MYJHXtIZiD1s4KZqb4q1J187gTcS
    - name: pyupio/safety-action
      uses: pyupio/safety-action@v1.0.1
            