language: python

python:
  - "3.11.9"

install:
  - pip install -r requirements-dev.txt

script:
  - flake8 .
  - isort .
  - black .
  - python manage.py test

after_success:
  - coveralls
env:
  global:
    - COVERALLS_REPO_TOKEN=4wTG5MYJHXtIZiD1s4KZqb4q1J187gTcS