runtime: python311
entrypoint: gunicorn -b :$PORT sitio.wsgi

env_variables:
  DJANGO_SETTINGS_MODULE: "sitio.settings"
  SECRET_KEY: "<your-secret-key>"
  DATABASE_URL: "https://rks-python.uc.r.appspot.com"


