# Generated by Django 5.1 on 2025-11-21 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_trainer_remove_schedule_instructor_schedule_trainers_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="Trainers",
        ),
        migrations.AddField(
            model_name="schedule",
            name="trainer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.trainer",
            ),
            preserve_default=False,
        ),
    ]
