# Generated by Django 5.1 on 2026-04-01 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_schedule_trainers_schedule_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('period', models.CharField(max_length=50, verbose_name='Período (ex: /mensal)')),
                ('description', models.TextField(verbose_name='Descrição Curta')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Mais Vendido?')),
                ('features', models.TextField(help_text='Insira cada benefício em uma nova linha.', verbose_name='Benefícios')),
                ('button1_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do Botão 1')),
                ('button1_url', models.URLField(blank=True, null=True, verbose_name='Link do Botão 1')),
                ('button2_text', models.CharField(blank=True, max_length=50, null=True, verbose_name='Texto do Botão 2')),
                ('button2_url', models.URLField(blank=True, null=True, verbose_name='Link do Botão 2')),
            ],
        ),
    ]
