# Generated by Django 5.1 on 2026-04-02 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_plan_options_plan_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
        ),
        migrations.AddField(
            model_name='plan',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Assinatura Recorrente Stone?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('diaria', 'Diária'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral')], default='mensal', max_length=20, verbose_name='Tipo de Vencimento'),
        ),
        migrations.CreateModel(
            name='ControleAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('status_catraca', models.CharField(choices=[('liberado', 'Liberado'), ('bloqueado', 'Bloqueado')], default='bloqueado', max_length=20, verbose_name='Status na Catraca')),
                ('aluno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acesso', to='blog.aluno', verbose_name='Aluno')),
            ],
        ),
        migrations.CreateModel(
            name='PagamentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transacao_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Transação Stone')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('recusado', 'Recusado')], default='pendente', max_length=20, verbose_name='Status')),
                ('metodo_pagamento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Método (Pix/Cartão)')),
                ('data_pagamento', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='blog.aluno', verbose_name='Aluno')),
                ('plano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.plan', verbose_name='Plano')),
            ],
        ),
    ]
