# Generated by Django 5.1 on 2026-04-02 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_aluno_plan_is_recurring_plan_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='is_recurring',
        ),
        migrations.AddField(
            model_name='plan',
            name='ton_link',
            field=models.URLField(blank=True, help_text='Cole o link de Venda da Ton correspondente a este pacote', null=True, verbose_name='Link de Pagamento Ton'),
        ),
    ]
