# Generated by Django 5.1 on 2026-04-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_plan_is_recurring_plan_ton_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='digital',
            field=models.TextField(blank=True, null=True, verbose_name='Digital (Template Biométrico)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alunos/fotos/', verbose_name='Foto (Reconhecimento Facial)'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Matrícula'),
        ),
    ]
