# Generated by Django 5.1 on 2026-04-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_aluno_digital_aluno_foto_aluno_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Imagem do Cabeçalho (Hero)')),
                ('hero_title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título do Hero')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo do Hero')),
                ('pricing_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Planos')),
                ('ps_parallax_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: PS (Rodapé Intro)')),
                ('contact_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Contato')),
                ('about_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Sobre Nós')),
                ('programs_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Modalidades')),
                ('trainers_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Professores')),
                ('schedule_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Cronograma')),
                ('blog_background', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Fundo Parallax: Blog')),
                ('intro_logo', models.ImageField(blank=True, null=True, upload_to='site_images/', verbose_name='Logo da Introdução')),
            ],
            options={
                'verbose_name': 'Configurações do Site',
                'verbose_name_plural': 'Configurações do Site',
            },
        ),
    ]
