# Generated by Django 5.1 on 2026-04-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_siteconfiguration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'verbose_name': 'Aluno para Matrícula', 'verbose_name_plural': '01. Gestão: Alunos para Matrícula'},
        ),
        migrations.AlterModelOptions(
            name='blogpost',
            options={'verbose_name': 'Postagem do Blog', 'verbose_name_plural': '08. Comunicação: Blog'},
        ),
        migrations.AlterModelOptions(
            name='controleacesso',
            options={'verbose_name': 'Controle de Acesso', 'verbose_name_plural': '04. Gestão: Controle de Acesso'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Evento', 'verbose_name_plural': '09. Comunicação: Eventos'},
        ),
        migrations.AlterModelOptions(
            name='pagamentohistorico',
            options={'verbose_name': 'Histórico de Pagamento', 'verbose_name_plural': '02. Gestão: Histórico de Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('order',), 'verbose_name': 'Plano e Pacote', 'verbose_name_plural': '03. Gestão: Planos e Pacotes'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': '05. Modalidades e Equipe: Programas'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'Cronograma', 'verbose_name_plural': '07. Modalidades e Equipe: Cronograma'},
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Design: Fotos do Site', 'verbose_name_plural': '00. Design: Fotos do Site'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Professor', 'verbose_name_plural': '06. Modalidades e Equipe: Professores'},
        ),
    ]
