# Generated by Django 5.1 on 2026-04-03 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_aluno_options_alter_blogpost_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='ton_link',
        ),
        migrations.AlterField(
            model_name='pagamentohistorico',
            name='transacao_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID da Transação (Referência)'),
        ),
    ]
