# Generated by Django 5.1 on 2026-04-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_plan_ton_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleacesso',
            name='abrir_catraca_agora',
            field=models.BooleanField(default=False, verbose_name='Liberar Catraca Agora?'),
        ),
    ]
