# Generated by Django 5.1 on 2026-04-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_controleacesso_abrir_catraca_agora'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='duration_days',
            field=models.IntegerField(default=30, help_text='Quantos dias de acesso liberar na catraca após o pagamento.', verbose_name='Dias de Acesso'),
        ),
    ]
