# Generated by Django 5.1 on 2026-04-04 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_plan_duration_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleacesso',
            name='plano_pendente',
            field=models.ForeignKey(blank=True, help_text='Plano pago, aguardando biometria para ativar e calcular vencimento.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acessos_pendentes', to='blog.plan', verbose_name='Plano Aguardando 1ª Entrada'),
        ),
        migrations.AlterField(
            model_name='controleacesso',
            name='status_catraca',
            field=models.CharField(choices=[('liberado', 'Liberado'), ('aguardando_biometria', 'Aguardando Biometria (Pago)'), ('bloqueado', 'Bloqueado')], default='bloqueado', max_length=25, verbose_name='Status na Catraca'),
        ),
    ]
