# Generated by Django 5.1 on 2026-04-04 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_controleacesso_plano_pendente_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Modalidade', 'verbose_name_plural': '05. Academia: Modalidades'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['day', 'start_time'], 'verbose_name': 'Horário de Funcionamento', 'verbose_name_plural': '07. Academia: Horários de Funcionamento'},
        ),
        migrations.AlterModelOptions(
            name='trainer',
            options={'verbose_name': 'Professor', 'verbose_name_plural': '06. Academia: Professores'},
        ),
        migrations.AddField(
            model_name='schedule',
            name='shift',
            field=models.CharField(choices=[('manha', 'Manhã'), ('meio_dia', 'Meio-dia'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', max_length=20, verbose_name='Turno'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='day',
            field=models.CharField(choices=[('monday', 'Segunda-feira'), ('tuesday', 'Terça-feira'), ('wednesday', 'Quarta-feira'), ('thursday', 'Quinta-feira'), ('friday', 'Sexta-feira'), ('saturday', 'Sábado'), ('sunday', 'Domingo')], max_length=10, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_time',
            field=models.TimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.program', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_time',
            field=models.TimeField(verbose_name='Início'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.trainer', verbose_name='Professor'),
        ),
    ]
