# Generated by Django 5.1 on 2026-04-04 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_program_options_alter_schedule_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='blog_background',
        ),
    ]
