# Generated by Django 5.1 on 2026-04-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0016_delete_blogpost_delete_event_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="program",
            options={
                "ordering": ("order",),
                "verbose_name": "Modalidade",
                "verbose_name_plural": "05. Academia: Modalidades",
            },
        ),
        migrations.AddField(
            model_name="program",
            name="order",
            field=models.PositiveIntegerField(
                db_index=True, default=0, editable=False, verbose_name="order"
            ),
            preserve_default=False,
        ),
    ]
