# Generated by Django 5.1 on 2026-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_program_options_program_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="controleacesso",
            name="status_catraca",
            field=models.CharField(
                choices=[
                    ("liberado", "Liberado"),
                    ("aguardando_biometria", "Aguardando Biometria (Pago)"),
                    (
                        "aguardando_pagamento",
                        "Aguardando Confirmação de Pagamento (PIX)",
                    ),
                    ("bloqueado", "Bloqueado"),
                ],
                default="bloqueado",
                max_length=25,
                verbose_name="Status na Catraca",
            ),
        ),
    ]
