# Generated by Django 5.1 on 2026-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_controleacesso_status_catraca"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfiguration",
            name="footer_logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="site_images/",
                verbose_name="Logo do Rodapé",
            ),
        ),
    ]
