# Generated by Django 5.1 on 2026-04-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_siteconfiguration_footer_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='infinitepay_link',
            field=models.URLField(blank=True, help_text='Link específico de pagamento deste plano na InfinitePay (ex: https://invoice.infinitepay.io/plans/rocks-fit/...)', null=True, verbose_name='Link InfinitePay (Checkout)'),
        ),
    ]
