# Generated by Django 5.1 on 2026-04-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_plan_infinitepay_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='icon',
            field=models.ImageField(blank=True, help_text='Envie um ícone (PNG/SVG) para representar esta modalidade nos horários e cards.', null=True, upload_to='program_icons/', verbose_name='Ícone da Modalidade'),
        ),
    ]
