# Generated by Django 5.1 on 2026-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_add_icon_to_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='card_button_text',
            field=models.CharField(blank=True, help_text="Texto exibido no botão do card de planos (ex: 'Assinar Agora'). Padrão: Assinar Agora", max_length=50, null=True, verbose_name='Texto do Botão no Card'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button1_text',
            field=models.CharField(blank=True, help_text='Texto do botão de pagamento via cartão na página de checkout.', max_length=100, null=True, verbose_name='Texto do Botão InfinitePay (Checkout)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='button2_text',
            field=models.CharField(blank=True, help_text='Texto do botão de pagamento via PIX na página de checkout.', max_length=100, null=True, verbose_name='Texto do Botão PIX (Checkout)'),
        ),
    ]
