# Generated by Django 5.1 on 2026-04-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_add_card_button_text_to_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Configuração do Site', 'verbose_name_plural': '00. Configurações do Site'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pix_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave PIX'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='pix/', verbose_name='QR Code do PIX (Imagem)'),
        ),
    ]
