# Generated by Django 5.1 on 2026-04-16 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_siteconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='instagram_url',
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Rede (ex: Instagram)')),
                ('link', models.URLField(verbose_name='Link do Perfil')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='social_icons/', verbose_name='Upload de Ícone (PNG/SVG)')),
                ('icon_url', models.URLField(blank=True, help_text='Use caso não queira fazer upload.', null=True, verbose_name='Ou URL do Ícone (Externo)')),
                ('site_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='blog.siteconfiguration', verbose_name='Desenvolvedor (Rodapé)')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='blog.trainer', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Rede Social',
                'verbose_name_plural': '08. Academia: Redes Sociais',
            },
        ),
    ]
