# Generated by Django 5.1 on 2026-04-16 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_trainer_instagram_url_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ('order',), 'verbose_name': 'Professor', 'verbose_name_plural': '06. Academia: Professores'},
        ),
        migrations.AddField(
            model_name='trainer',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DeveloperSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Rede (ex: LinkedIn)')),
                ('link', models.URLField(verbose_name='Link do Perfil')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='social_icons/dev/', verbose_name='Upload de Ícone (PNG/SVG)')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Ou URL do Ícone (Externo)')),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='blog.siteconfiguration', verbose_name='Desenvolvedor (Rodapé)')),
            ],
            options={
                'verbose_name': 'Rede Social do Desenvolvedor',
                'verbose_name_plural': '09. Academia: Redes Sociais do Desenvolvedor',
            },
        ),
        migrations.CreateModel(
            name='TrainerSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome da Rede (ex: Instagram)')),
                ('link', models.URLField(verbose_name='Link do Perfil')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='social_icons/trainers/', verbose_name='Upload de Ícone (PNG/SVG)')),
                ('icon_url', models.URLField(blank=True, null=True, verbose_name='Ou URL do Ícone (Externo)')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='blog.trainer', verbose_name='Professor')),
            ],
            options={
                'verbose_name': 'Rede Social do Professor',
                'verbose_name_plural': '08. Academia: Redes Sociais dos Professores',
            },
        ),
        migrations.DeleteModel(
            name='SocialMedia',
        ),
    ]
