# Generated by Django 5.1 on 2026-04-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_trainer_options_trainer_order_developersocial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_description',
            field=models.TextField(blank=True, default='Desenvolvido por Cleyson Cassio - Eng. de Software', null=True, verbose_name='Descrição do Rodapé'),
        ),
    ]
