# Generated by Django 5.1 on 2026-04-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_siteconfiguration_footer_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aluno_perfil', to='blog.user', verbose_name='Usuário de Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('SECRETARIA', 'Secretaria'), ('PROFESSOR', 'Professor'), ('ALUNO', 'Aluno')], default='ALUNO', max_length=20, verbose_name='Cargo'),
        ),
    ]
