# Generated by Django 5.1 on 2026-04-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_aluno_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('SUSPENSO', 'Suspenso'), ('INADIMPLENTE', 'Inadimplente'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=15, verbose_name='Status de Gestão'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='valor_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Último Valor Pago'),
        ),
    ]
