# Generated by Django 5.1 on 2026-04-17 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_aluno_status_aluno_valor_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentohistorico',
            options={'verbose_name': 'Histórico de Pagamento', 'verbose_name_plural': '02. Gestão: Históricos de Pagamentos'},
        ),
        migrations.RemoveField(
            model_name='pagamentohistorico',
            name='metodo_pagamento',
        ),
        migrations.AddField(
            model_name='pagamentohistorico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='pagamentohistorico',
            name='data_pagamento',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data do Pagamento'),
        ),
        migrations.CreateModel(
            name='CaixaTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abertura', models.DateTimeField(auto_now_add=True)),
                ('fechamento', models.DateTimeField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado')], default='ABERTO', max_length=10)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Turno de Caixa',
                'verbose_name_plural': '10. Financeiro: Turnos de Caixa',
            },
        ),
        migrations.CreateModel(
            name='TransacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (+)'), ('SAIDA', 'Saída (-)')], max_length=10)),
                ('origem', models.CharField(choices=[('MANUAL', 'Manual'), ('SITE', 'Site/Web'), ('APP', 'Aplicativo')], default='MANUAL', max_length=10)),
                ('metodo', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('CREDITO', 'Cartão de Crédito'), ('DEBITO', 'Cartão de Débito')], max_length=15)),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='blog.caixaturno')),
            ],
            options={
                'verbose_name': 'Movimentação de Caixa',
                'verbose_name_plural': '11. Financeiro: Movimentações',
            },
        ),
    ]
