# Generated by Django 5.1 on 2026-04-17 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_pagamentohistorico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.program', verbose_name='Modalidade'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.trainer', verbose_name='Professor'),
        ),
    ]
