# Generated by Django 5.1 on 2026-04-17 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_schedule_program_alter_schedule_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixaturno',
            name='is_automatico',
            field=models.BooleanField(default=False, verbose_name='Fechamento Automático?'),
        ),
        migrations.AddField(
            model_name='pagamentohistorico',
            name='metodo_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Método de Pagamento'),
        ),
        migrations.AlterField(
            model_name='caixaturno',
            name='saldo_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Final (Fechamento)'),
        ),
        migrations.AlterField(
            model_name='caixaturno',
            name='saldo_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Inicial (Abertura)'),
        ),
    ]
