# Generated by Django 5.1 on 2026-04-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_trainer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacaocaixa',
            name='status',
            field=models.CharField(choices=[('NORMAL', 'Ativa'), ('ESTORNADO', 'Estornada')], default='NORMAL', max_length=15),
        ),
    ]
