# Generated by Django 5.1 on 2026-04-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_transacaocaixa_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Rocks-Fit', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='gym_logos/')),
            ],
            options={
                'verbose_name': 'Configuração da Academia',
                'verbose_name_plural': 'Configuração da Academia',
            },
        ),
    ]
