# Generated by Django 5.1 on 2026-04-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_gymsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_access_financial', 'Pode acessar o módulo financeiro e caixa'), ('can_manage_students', 'Pode cadastrar e gerenciar alunos'), ('can_manage_workouts', 'Pode gerenciar treinos e avaliações'), ('can_access_settings', 'Pode acessar configurações do gestor')]},
        ),
    ]
