# Generated by Django 5.1 on 2026-04-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='controleacesso',
            name='esta_dentro',
            field=models.BooleanField(default=False, verbose_name='Está Dentro da Academia?'),
        ),
        migrations.AddField(
            model_name='controleacesso',
            name='ultimo_acesso',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Último Acesso'),
        ),
    ]
