# Generated by Django 5.1 on 2026-04-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_controleacesso_esta_dentro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_convenio',
            field=models.BooleanField(default=False, verbose_name='É Convênio? (Wellhub/TotalPass)'),
        ),
    ]
