# Generated by Django 5.1 on 2026-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_aluno_bairro_aluno_cep_aluno_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AGUARDANDO', 'Aguardando Pagamento'), ('SUSPENSO', 'Suspenso'), ('INADIMPLENTE', 'Inadimplente'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=15, verbose_name='Status de Gestão'),
        ),
    ]
