# Generated by Django 5.1 on 2026-04-21 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0040_alter_aluno_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'permissions': [('can_manage_students', 'Pode gerenciar alunos no CRM'), ('can_access_financial', 'Pode acessar o setor financeiro')], 'verbose_name': 'Aluno', 'verbose_name_plural': '02. Gestão: Alunos'},
        ),
    ]
