# Generated by Django 5.1 on 2026-04-23 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("blog", "0041_alter_aluno_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_identifier",
                    models.CharField(max_length=255, verbose_name="Email/CPF"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(verbose_name="Endereço IP"),
                ),
                (
                    "user_agent",
                    models.CharField(max_length=255, verbose_name="User Agent"),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="Sucesso?"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso",
                "verbose_name_plural": "Logs de Acessos",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("can_manage_users", "Pode gerenciar usuários staff"),
                    ("can_manage_memberships", "Pode gerenciar planos e matrículas"),
                    (
                        "can_view_financial_reports",
                        "Pode visualizar relatórios financeiros",
                    ),
                    ("can_manage_schedule", "Pode gerenciar horários e turmas"),
                    ("can_checkin", "Pode realizar check-in na catraca"),
                    ("can_manage_nutrition", "Pode gerenciar avaliações e cardápios"),
                    ("can_view_student_data", "Pode visualizar dados dos alunos"),
                    ("can_manage_trainings", "Pode gerenciar diários de treino"),
                    (
                        "can_view_system_logs",
                        "Pode visualizar logs de auditoria do sistema",
                    ),
                ],
                "verbose_name": "Usuário",
                "verbose_name_plural": "Usuários",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="user",
            name="birth_date",
        ),
        migrations.RemoveField(
            model_name="user",
            name="location",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.RemoveField(
            model_name="user",
            name="website",
        ),
        migrations.AddField(
            model_name="user",
            name="cpf",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=14,
                null=True,
                unique=True,
                verbose_name="CPF",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data de Nascimento"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_2fa_enabled",
            field=models.BooleanField(default=False, verbose_name="2FA Ativado"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_ip",
            field=models.GenericIPAddressField(
                blank=True, null=True, verbose_name="Último IP"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_login_user_agent",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Último User Agent"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefone"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("superadmin", "SuperAdmin"),
                    ("admin", "Administrador"),
                    ("secretary", "Secretário(a)"),
                    ("trainer", "Professor(a)"),
                    ("nutritionist", "Nutricionista"),
                    ("student", "Aluno(a)"),
                ],
                default="student",
                max_length=20,
                verbose_name="Tipo de Usuário",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
        migrations.CreateModel(
            name="Nutritionist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "crn",
                    models.CharField(max_length=20, unique=True, verbose_name="CRN"),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Especialidade",
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="nutritionist_images/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutritionist_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário de Login",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutricionista",
                "verbose_name_plural": "06b. Academia: Nutricionistas",
            },
        ),
    ]
