# Generated by Django 5.1 on 2026-04-23 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0042_loginattempt_alter_user_options_remove_user_bio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="cpf",
            field=models.CharField(
                blank=True, max_length=14, null=True, unique=True, verbose_name="CPF"
            ),
        ),
        migrations.AlterField(
            model_name="nutritionist",
            name="crn",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="CRN"
            ),
        ),
    ]
