# Generated by Django 5.1 on 2026-04-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('blog', '0043_alter_aluno_cpf_alter_nutritionist_crn'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superadmin', 'SuperAdmin'), ('admin', 'Administrador'), ('secretary', 'Secretário(a)'), ('trainer', 'Professor(a)'), ('nutritionist', 'Nutricionista'), ('student', 'Aluno(a)')], max_length=20, unique=True, verbose_name='Cargo')),
                ('permissions', models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permissões Ativas')),
            ],
            options={
                'verbose_name': 'Configuração de Cargo',
                'verbose_name_plural': '06c. Configurações: Permissões por Cargo',
            },
        ),
    ]
