# Generated by Django 5.1 on 2026-04-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0044_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('diaria', 'Diária'), ('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('bienal', 'Bienal'), ('personalizado', 'Personalizado (Ver campo Dias)')], default='mensal', max_length=20, verbose_name='Tipo de Vencimento'),
        ),
    ]
