# Generated by Django 5.1 on 2026-04-24 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_alter_plan_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsetting',
            name='juros_mensal',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Percentual de juros aplicado por mês de atraso.', max_digits=5, verbose_name='Juros Mensais (%)'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='msg_aniversario',
            field=models.CharField(default='Parabéns! A Rocks Fit deseja um feliz aniversário! 🎉', max_length=255, verbose_name='Mensagem de Aniversário'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='msg_bloqueio_crm',
            field=models.CharField(default='Cadastro Suspenso/Inativo. Procure a recepção.', max_length=255, verbose_name='Mensagem de Bloqueio (Administrativo)'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='msg_erro_wellhub',
            field=models.CharField(default='Erro no plano Wellhub/Gympass. Valide no app.', max_length=255, verbose_name='Mensagem Erro Corporativo'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='multa_atraso',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Percentual fixo aplicado sobre o valor da mensalidade atrasada.', max_digits=5, verbose_name='Multa por Atraso (%)'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='whatsapp_notificacao',
            field=models.CharField(blank=True, help_text='Número que o aluno deve chamar ao ser barrado.', max_length=20, null=True, verbose_name='WhatsApp para Suporte'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('AGUARDANDO', 'Aguardando Pagamento'), ('SUSPENSO', 'Suspenso'), ('INADIMPLENTE', 'Inadimplente'), ('INATIVO', 'Inativo')], default='INATIVO', max_length=15, verbose_name='Status de Gestão'),
        ),
    ]
