# Generated by Django 5.1 on 2026-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_gymsetting_juros_mensal_gymsetting_msg_aniversario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsetting',
            name='catraca_fluxo',
            field=models.CharField(choices=[('ENTRADA', 'Apenas Entrada'), ('SAIDA', 'Apenas Saída'), ('BIDIRECIONAL', 'Alternar Entrada/Saída Auto')], default='BIDIRECIONAL', max_length=20, verbose_name='Controle de Fluxo'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='msg_entrada',
            field=models.CharField(default='Bom treino!', max_length=255, verbose_name='Mensagem de Entrada'),
        ),
        migrations.AddField(
            model_name='gymsetting',
            name='msg_saida',
            field=models.CharField(default='Bom descanso!', max_length=255, verbose_name='Mensagem de Saída'),
        ),
    ]
