# Generated by Django 5.1 on 2026-05-05 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0047_gymsetting_catraca_fluxo_gymsetting_msg_entrada_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcaoIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_acao",
                    models.CharField(max_length=100, verbose_name="ID da Ação"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("POST_REDE_SOCIAL", "Post Rede Social"),
                            ("MENSAGEM_WHATSAPP", "Mensagem WhatsApp"),
                            ("CAMPANHA_EMAIL", "Campanha de E-mail"),
                            ("OUTRO", "Outro"),
                        ],
                        max_length=50,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "titulo_painel",
                    models.CharField(max_length=255, verbose_name="Título no Painel"),
                ),
                (
                    "detalhes_para_aprovacao",
                    models.TextField(verbose_name="Detalhes para Aprovação"),
                ),
                ("payload", models.JSONField(verbose_name="Dados da Ação (Payload)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDENTE", "Pendente"),
                            ("APROVADO", "Aprovado"),
                            ("REJEITADO", "Rejeitado"),
                            ("EXECUTADO", "Executado"),
                        ],
                        default="PENDENTE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
            ],
            options={
                "verbose_name": "Ação de IA",
                "verbose_name_plural": "Ações de IA",
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="AnaliseGeralIA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "risco_evasao_percentual",
                    models.FloatField(verbose_name="Risco de Evasão (%)"),
                ),
                ("saude_financeira", models.TextField(verbose_name="Saúde Financeira")),
                ("insight_do_dia", models.TextField(verbose_name="Insight do Dia")),
                (
                    "data_analise",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Análise"
                    ),
                ),
            ],
            options={
                "verbose_name": "Análise Geral de IA",
                "verbose_name_plural": "Análises Gerais de IA",
                "ordering": ["-data_analise"],
            },
        ),
        migrations.AddField(
            model_name="gymsetting",
            name="ai_api_key",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="API Key (OpenRouter/Qwen)",
            ),
        ),
        migrations.AddField(
            model_name="gymsetting",
            name="ai_system_prompt",
            field=models.TextField(
                blank=True, null=True, verbose_name="Prompt de Sistema da IA"
            ),
        ),
    ]
