# Generated by Django 5.1 on 2026-05-05 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0048_acaoia_analisegeralia_gymsetting_ai_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcessoLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data_hora",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data/Hora"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        default="ENTRADA",
                        max_length=10,
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="acessos",
                        to="blog.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de Acesso",
                "verbose_name_plural": "Logs de Acessos",
                "ordering": ["-data_hora"],
            },
        ),
    ]
