# Generated by Django 5.1 on 2026-05-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0049_acessolog"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="facial_embedding",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Embedding Facial (ArcFace)"
            ),
        ),
        migrations.AlterField(
            model_name="acessolog",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("ENTRADA", "Entrada"),
                    ("SAIDA", "Saída"),
                    ("NEGADO", "Acesso Negado"),
                ],
                default="ENTRADA",
                max_length=10,
            ),
        ),
    ]
