# Generated by Django 5.1 on 2026-05-23 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_aluno_facial_embedding_alter_acessolog_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentohistorico',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Recebido por'),
        ),
    ]
