# Generated by Django 5.1 on 2026-05-24 01:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0051_pagamentohistorico_operador"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentohistorico",
            name="data_pagamento",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Data do Pagamento"
            ),
        ),
    ]
