# Generated by Django 5.1 on 2026-05-24 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0052_alter_pagamentohistorico_data_pagamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="controleacesso",
            name="dias_congelados",
            field=models.IntegerField(
                default=0, verbose_name="Dias de Crédito Congelados"
            ),
        ),
    ]
