# Generated by Django 5.1 on 2026-05-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0053_controleacesso_dias_congelados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagamentohistorico",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("pago", "Pago"),
                    ("recusado", "Recusado"),
                    ("estornado", "Estornado"),
                ],
                default="pendente",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
