# Generated by Django 5.1 on 2026-05-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0054_alter_pagamentohistorico_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymsetting",
            name="dias_tolerancia",
            field=models.IntegerField(
                default=0,
                help_text="Quantos dias o aluno pode continuar passando na catraca após o vencimento do plano.",
                verbose_name="Crédito de Tolerância (Dias)",
            ),
        ),
    ]
