# Generated by Django 5.1 on 2026-05-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0055_gymsetting_dias_tolerancia"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="data_cancelamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="Data do Cancelamento"
            ),
        ),
        migrations.AddField(
            model_name="aluno",
            name="motivo_cancelamento",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Motivo do Cancelamento",
            ),
        ),
    ]
