# Generated by Django 5.1 on 2026-05-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0056_aluno_data_cancelamento_aluno_motivo_cancelamento"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymsetting",
            name="evolution_api_key",
            field=models.CharField(
                default="429683C4C977415CBEE243405C76100E",
                max_length=255,
                verbose_name="API Key (Global) da Evolution",
            ),
        ),
        migrations.AddField(
            model_name="gymsetting",
            name="evolution_api_url",
            field=models.CharField(
                default="http://localhost:8080",
                max_length=255,
                verbose_name="URL da Evolution API",
            ),
        ),
        migrations.AddField(
            model_name="gymsetting",
            name="evolution_instance_name",
            field=models.CharField(
                default="Rocksfit-business",
                max_length=100,
                verbose_name="Nome da Instância",
            ),
        ),
    ]
