# Generated by Django 5.1 on 2026-05-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0057_gymsetting_evolution_api_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampanhaAutomacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, verbose_name="Descrição da Campanha"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("pausada", "Pausada"),
                            ("rascunho", "Rascunho"),
                        ],
                        default="rascunho",
                        max_length=20,
                    ),
                ),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("baixa", "Baixa"),
                            ("media", "Média"),
                            ("alta", "Alta"),
                        ],
                        default="media",
                        max_length=10,
                    ),
                ),
                (
                    "gatilho",
                    models.CharField(
                        choices=[
                            ("data", "Data & Hora Agendada"),
                            ("checkin", "No Check-in do Membro"),
                            ("cadastro", "No Novo Cadastro"),
                            ("pagamento", "No Sucesso do Pagamento"),
                            ("pesquisa", "Envio de Pesquisa de Opinião"),
                        ],
                        max_length=20,
                    ),
                ),
                ("horario_disparo", models.DateTimeField(blank=True, null=True)),
                ("repetir", models.BooleanField(default=False)),
                ("dimensao", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status_audiencia",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("canal_whatsapp", models.BooleanField(default=True)),
                ("canal_email", models.BooleanField(default=False)),
                ("canal_app", models.BooleanField(default=False)),
                ("conteudo", models.TextField(verbose_name="Conteúdo da Mensagem")),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Campanha de Automação",
                "verbose_name_plural": "Campanhas de Automações",
                "ordering": ["-criado_em"],
            },
        ),
    ]
