# Generated by Django 5.1 on 2026-05-30 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0058_campanhaautomacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remetente', models.CharField(max_length=50, verbose_name='Número do WhatsApp')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Enviado pelo Bot?')),
                ('texto', models.TextField(verbose_name='Texto da Mensagem')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mensagem de Chat (IA)',
                'verbose_name_plural': 'Histórico de Chat (IA)',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='campanhaautomacao',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Campanha de Automação', 'verbose_name_plural': 'Campanhas de Automação'},
        ),
        migrations.AddField(
            model_name='aluno',
            name='bot_ativo',
            field=models.BooleanField(default=True, help_text='Se falso, o bot de IA ignora as mensagens deste aluno (útil para atendimento humano).', verbose_name='Bot do WhatsApp Ativo'),
        ),
    ]
