# Generated by Django 5.1 on 2026-05-30 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0059_chatmessage_alter_campanhaautomacao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymsetting',
            name='is_ia_active',
            field=models.BooleanField(default=True, verbose_name='Ativar IA no WhatsApp'),
        ),
    ]
