version: '3.3'

services:
  evolution-api:
    image: atendai/evolution-api:v2.2.1
    container_name: evolution-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SERVER_URL=https://sua-evolution-api.hostman.site
      - CONFIG_SESSION_PHONE_CLIENT=RocksFit
      - CONFIG_SESSION_PHONE_NAME=chrome
      - DEL_INSTANCE=false
      
      # Autenticação (A CHAVE GLOBAL SECRETA)
      - AUTHENTICATION_TYPE=apikey
      - AUTHENTICATION_API_KEY=429683C4C977415CBEE243405C76100E
      - AUTHENTICATION_EXPOSE_IN_ENV=true

      # Configuração de Banco de Dados (Usando sqlite para facilidade no Hostman)
      - DATABASE_ENABLED=false
      
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_store:/evolution/store

volumes:
  evolution_instances:
  evolution_store:
